export const strings = {
  PROMPT: 'Do you want to Login or Create an account?',
  BTN_CREATE: 'Create an account',
  BTN_LOGIN: 'Log-in',
  SWITCH_MOBILE: 'Mobile',
  SWITCH_EMAIL: 'Email',
  LABEL_EMAIL_ADDRESS: 'Email Address',
  EMAIL_PLACEHOLDER: 'Enter your Email',
  MOBILE_PLACEHOLDER: 'Enter your number',
  OTP_PLACEHOLDER: 'Enter OTP',
  ADD_PROFILE_PICTURE: 'Add Profile Picture',
  LABEL_FULL_NAME: 'Full Name',
  FULL_NAME_PLACEHOLDER: 'Enter your Full Name',
  LABEL_CADRE_TYPE: 'Cadre Type',
  CADRE_LEVEL: 'Select cadre level',
  CADRE: 'Select cadre',
  DISTRICT: 'Select District',
  TU: 'Select TU',
  HEALTH_FACILITY: 'Select Health Facility',
  NOT_AVAILABLE: 'Not Available',
  EDIT_PICTURE: 'Edit Picture',
  LOADING: 'Loading...',
  GEOGRAPHIC_DETAILS: 'Geographic Details',
  STATE: 'State',
  DISTRICT_LABEL: 'District',
  HEALTH_FACILITY_LABEL: 'Health Facility',
  OTP_INVALID: 'Invalid OTP!',
  CONTACT_EXIST: 'This phone number is already registered. Please Login.',
  EMAIL_EXIST: 'This email is already registered. Please Login.',
  CONTACT_INVALID: 'Invalid contact number!',
  EMAIL_INVALID: 'Invalid email format',
  EMAIL_REQUIRED: 'Email is required',
  GREETING: 'Hi! 😊',
  PROFILE_UPDATED: 'Your profile has been successfully updated.',
  LOADING_MORE: 'Loading more...',
  INTRO:
    'Hmm, I couldn’t locate the information you need. Try asking differently or let me know how else I can help!',
  ASK: 'Choose a topic or type your question here.',
  SUBJECT_LENGTH: 'Please enter a subject with at least 5 characters.',
  SUBJECT_REQUIRED: 'Subject is required',
  MESSAGE_LENGTH: 'Message should be at least 10 characters',
  MESSAGE_REQUIRED: 'Message is required',
  FACEBOOK: 'https://www.facebook.com/profile.php?id=100086461717566',
  TWITTER: 'https://twitter.com/NikshaySetu',
  INSTAGRAM: 'https://www.instagram.com/nikshaysetu/',
  POLICY: 'Privacy Policy',
  FOLLOW_US: 'Follow us on social media',
  SUCCESS: 'Submitted Successfully',
  SUBJECT: 'Subject',
  SUBJECT_PLACEHOLDER: 'Enter subject',
  MESSAGE: 'Message',
  MESSAGE_PLACEHOLDER: 'Write message',
  SUBMIT: 'Submit',
  IN_DEVELOPMENT:
    'Thanks for your interest! The course for your cadre is in progress. It will be available soon, and we appreciate your patience!',
  MANAGE_TB:
    'Manage TB India simplifies TB care, ensuring evidence-based prescriptions for all types of TB, including DR-TB',
  PARTNERS: 'The Union - IIPHG - NITRD',
  NAME: 'Patient Name:',
  DIAGNOSIS: 'Diagnosis',
  REGIMEN: 'The recommended treatment regimen for the patient is:',
  PRESCRIPTION: 'Prescription',
  NOTES: 'Notes',
  ADDITIONAL: 'Additional Tools',
  SCREENING: 'Screening Tool',
  TREATMENT: 'Treatment',
  TPT: 'TPT',
  ADHERENCE: 'Differentiated Care',
  REFERRAL: 'Referral Health Facilities',
  RESOURCE: 'Resource Material',
  GUIDELINES: 'Guidelines',
  ORDERS: 'Office Orders',
  VIDEOS: 'Videos',
  DOCUMENTS: 'Documents',
  ASSESSMENTS: 'Assessments',
  CURRENT_ASSESSMENTS: 'Current Assessments',
  PAST_ASSESSMENTS: 'Past Assessments',
  CERTIFICATES: 'Certificates',
  INTERACTION: 'Application Interaction',
  SURVEY_FORM: 'Survey Form',
  CONTACT_US: 'Contact Us',
  RATING: 'Rating',
  MANAGE_TB_TITLE: 'ManageTB India',
  TO_COE: 'Raise a clinical query to CoE',
  TRACK: 'Track a Query',
  PENDING: 'You have unanswered queries waiting.',
  DATE: 'Date of Admission',
  OPTIONAL_COMPLAINT: 'Chief Complaint (Optional)',
  OPTIONAL_HISTORY: 'History of present illness & duration (Optional)',
  OPTIONAL_PAST_HISTORY: 'Past history/Follow-up history (If any)(Optional)',
  OPTIONAL_PRE_TREATMENT: 'Pre-treatment evaluation findings (Optional)',
  OPTIONAL_ASSESSMENT: 'Assessment and differential diagnosis (Optional)',
  OPTIONAL_TREATMENT_PLAN: 'Ongoing Treatment Plan (Optional)',
  SEARCH: 'Locate Nearby Health Centers',
  PROCESS: 'Process of diagnosis of Pulmonary TB',
  DESCRIPTION:
    'Medical Officers should identify all pulmonary TB suspects and refer them for sputum examination using the NTEP laboratory request form.',
  TITLE: 'Tools for diagnosis of Pulmonary TB in adults:',
  DESIRABLE_WEIGHT: 'Desirable Weight',
  MIN_WEIGHT: 'Minimum acceptable weight',
  WEIGHT_GAIN: 'Desirable Weight gain',
  MIN_GAIN: 'Minimum weight gain required',
  CALORIC_INTAKE: 'Desirable Daily caloric intake',
  PROTEIN_INTAKE: 'Desirable Daily Protein Intake Range',
  MANAGEMENT: 'Nutrition Management',
  RESULT:
    'Based on the details, it suggests the individual might be at risk for:',
  THANKS: 'We appreciate your input!',
  SCREENING_TOOL_INTRO:
    'This tool helps determine if symptoms suggest the need for TB testing.',
  START: 'Start Now',
  SURVEY_PROMPT:
    'This survey helps us understand your needs to create better content.',
  THANK_YOU: 'Thanks for completing the survey!',
  APPRECIATION:
    'Thank you for your time! Your feedback will help us enhance our services.',
  COMPLETED: 'Completed ✓',
  ADVICE: 'Looking for expert guidance?',
  KNOWLEDGE_QUIZ_TITLE: 'knowledge Quiz',
  DMC: 'DMC',
  TRUNAT: 'TRUNAT',
  CBNAAT: 'CBNAAT',
  XRAY: 'X-Ray',
  ICTC: 'ICTC',
  LPA_LAB: 'LPA Lab',
  CONFIRMATION_CENTER: 'Confirmation Center',
  TOBACCO_CESSATION: 'Tobacco Cessation Clinic',
  ANC_CLINIC: 'ANC Clinic',
  NUTRITIONAL_REHAB: 'Nutritional Rehabilitation Center',
  DE_ADDICTION: 'De Addiction Centres',
  ART_CENTER: 'ART Center',
  DRTB_DISTRICT: 'District DRTB Centre',
  DRTB_NODAL: 'Nodal DRTB Center',
  IRL: 'IRL',
  PEDIATRIC_CARE: 'Child Health Care Center',
  VIEW_ALL: 'View all',
  NO_MORE_DATA: 'No additional records found.',
  SORT_BY_NAME: 'Organize by Name',
  SORT_BY_DATE: 'Arrange by Date',
  GREETING_MORNING: 'Good Morning!',
  GREETING_AFTERNOON: 'Good Afternoon!',
  GREETING_EVENING: 'Good Evening!',
  GREETING_HELP: 'How may I help you today?',
};
